services:
  chthon-mc:
    build:
      context: .
    container_name: chthon-mc
    cap_drop:
      - ALL
    cap_add:
      - SYS_RESOURCE
    devices:
      - /dev/fuse
    hostname: chthon-mc
    image: ghcr.io/drewrjensen/chthon-mc:${TAG}
    # image: drewrjensen/chthon-mc:TESTING
    labels:
      - "com.docker.compose.project=chthon-mc"
      - "com.docker.compose.service=chthon-mc"
      - "com.docker.compose.version=${VERSION}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8080:8080
      - 19132:19132
      - 24454:24454
      - 25565:25565
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stdin_open: true
    stop_grace_period: 30s
    stop_signal: SIGTERM
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    working_dir: /srv/papermc
    volumes:
      - /srv/papermc/plugins:/srv/papermc/plugins
      - /srv/papermc/worlds:/srv/papermc/worlds