apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chthon-mc-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mc.chthon.xyz`)
      kind: Rule
      services:
        - name: chthon-mc-web
          port: 8080
    - match: Host(`mc.chthon.xyz`) && PathPrefix(`/stats`)
      kind: Rule
      services:
        - name: chthon-mc-web
          port: 8804
