apiVersion: v1
kind: ConfigMap
metadata:
  name: chthon-mc-env
data:
  MC_VERSION: "${MC_VERSION}"
  CMC_VERSION: "${CMC_VERSION}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chthon-mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chthon-mc
  template:
    metadata:
      labels:
        app: chthon-mc
    spec:
      nodeSelector:
        kubernetes.io/hostname: chthon-srv-0
      hostNetwork: false
      containers:
        - name: minecraft
          image: ghcr.io/drewrjensen/chthon-mc:${MC_VERSION}-${CMC_VERSION}
          ports:
            - containerPort: 8080
              protocol: TCP
              hostPort: 8080
            - containerPort: 8804
              protocol: TCP
              hostPort: 8804
            - containerPort: 19132
              protocol: UDP
              hostPort: 19132
            - containerPort: 19133
              protocol: UDP
              hostPort: 19133
            - containerPort: 24454
              protocol: UDP
              hostPort: 24454
            - containerPort: 25565
              protocol: TCP
              hostPort: 25565
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms2G -Xmx8G"
          envFrom:
            - configMapRef:
                name: chthon-mc-env
          volumeMounts:
            - name: host-worlds
              mountPath: /srv/papermc/worlds
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "2"
      volumes:
        - name: host-worlds
          hostPath:
            path: /opt/minecraft/worlds
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: chthon-mc-web
spec:
  selector:
    app: chthon-mc
  ports:
    - name: dynmap
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: plan
      port: 8804
      targetPort: 8804
      protocol: TCP
